# Generated by Django 4.2.3 on 2023-07-12 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('matchId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('matchName', models.CharField(max_length=100)),
                ('dateTime', models.DateTimeField(verbose_name='date')),
                ('duration', models.FloatField(default=0)),
                ('ticks', models.IntegerField(default=0)),
                ('team1Name', models.CharField(max_length=100)),
                ('team2Name', models.CharField(max_length=100)),
                ('team1Score', models.IntegerField(default=0)),
                ('team2Score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('seriesName', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steamid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.series'),
        ),
        migrations.CreateModel(
            name='Hurt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steamid', models.CharField(max_length=100)),
                ('nadeDamage', models.IntegerField(default=0)),
                ('molotovDamage', models.IntegerField(default=0)),
                ('incendiaryDamage', models.IntegerField(default=0)),
                ('roundNumber', models.IntegerField(default=0)),
                ('tick', models.IntegerField(default=0)),
                ('hurtedSteamid', models.CharField(max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
            ],
        ),
    ]
