# Generated by Django 4.2.3 on 2023-07-11 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriesName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchId', models.CharField(max_length=100)),
                ('matchName', models.CharField(max_length=100)),
                ('dateTime', models.DateField()),
                ('duration', models.FloatField()),
                ('ticks', models.IntegerField()),
                ('team1Name', models.CharField(max_length=100)),
                ('team2Name', models.CharField(max_length=100)),
                ('team1Score', models.IntegerField()),
                ('team2Score', models.IntegerField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.series')),
            ],
        ),
        migrations.CreateModel(
            name='Hurt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steamid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('nadeDamage', models.IntegerField()),
                ('molotovDamage', models.IntegerField()),
                ('incendiaryDamage', models.IntegerField()),
                ('roundNumber', models.IntegerField()),
                ('tick', models.IntegerField()),
                ('hurtedSteamid', models.CharField(max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
            ],
        ),
    ]
